- name: Check for available updates (Debian/Ubuntu)
  hosts: all
  become: yes
  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes
      when: "ansible_os_family == 'Debian'"
    - name: Upgrade packages
      apt:
        upgrade: yes
