---
- name: Update chrony.conf file
  hosts: all
  become: yes
  tasks:
    - name: Update chrony.conf file
      template:
        src: ntp.conf.j2
        dest: /etc/chrony/chrony.conf
      notify: Restart chronyd
  handlers:
    - name: Restart chronyd
      service:
        name: chronyd
        state: restarted



