---
- name: Configure NTP Server
  hosts: all
  become: yes
  tasks:
    - name: Configure NTP servers
      template:
        src: ntp.conf.j2
        dest: /etc/chrony/chrony.conf
      notify: Restart chronyd
  handlers:
    - name: Restart chronyd
      service:
        name: chronyd
        state: restarted



